version: '2.1'
services:
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:nightly
    environment:
      # Enable health and metrics support
      - KC_HTTP_PORT=89
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth
    volumes:
      - ./export:/opt/keycloak/data/import
    command:
      - start-dev 
      - --import-realm
    ports:
      - "89:89"
 